# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simpleMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simpleMessage.proto',
  package='nats_schema',
  syntax='proto3',
  serialized_pb=_b('\n\x13simpleMessage.proto\x12\x0bnats_schema\")\n\rSimpleMessage\x12\n\n\x02ID\x18\x01 \x01(\x03\x12\x0c\n\x04\x42ody\x18\x02 \x01(\x0c\"\x1d\n\x0cMessageInt64\x12\r\n\x05Int64\x18\x01 \x01(\x03\"\'\n\x11MessageInt64Slice\x12\x12\n\nInt64Slice\x18\x01 \x03(\x03\"\x1b\n\x0bMessageBool\x12\x0c\n\x04\x42ool\x18\x01 \x01(\x08\"\x1d\n\x0cMessageBytes\x12\r\n\x05\x42ytes\x18\x01 \x01(\x0c\")\n\x0cRequestInt64\x12\n\n\x02ID\x18\x01 \x01(\x03\x12\r\n\x05Int64\x18\x02 \x01(\x03\")\n\x0cRequestBytes\x12\n\n\x02ID\x18\x01 \x01(\x03\x12\r\n\x05\x42ytes\x18\x02 \x01(\x0c\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SIMPLEMESSAGE = _descriptor.Descriptor(
  name='SimpleMessage',
  full_name='nats_schema.SimpleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='nats_schema.SimpleMessage.ID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Body', full_name='nats_schema.SimpleMessage.Body', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=77,
)


_MESSAGEINT64 = _descriptor.Descriptor(
  name='MessageInt64',
  full_name='nats_schema.MessageInt64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Int64', full_name='nats_schema.MessageInt64.Int64', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=108,
)


_MESSAGEINT64SLICE = _descriptor.Descriptor(
  name='MessageInt64Slice',
  full_name='nats_schema.MessageInt64Slice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Int64Slice', full_name='nats_schema.MessageInt64Slice.Int64Slice', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=149,
)


_MESSAGEBOOL = _descriptor.Descriptor(
  name='MessageBool',
  full_name='nats_schema.MessageBool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Bool', full_name='nats_schema.MessageBool.Bool', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=178,
)


_MESSAGEBYTES = _descriptor.Descriptor(
  name='MessageBytes',
  full_name='nats_schema.MessageBytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Bytes', full_name='nats_schema.MessageBytes.Bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=209,
)


_REQUESTINT64 = _descriptor.Descriptor(
  name='RequestInt64',
  full_name='nats_schema.RequestInt64',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='nats_schema.RequestInt64.ID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Int64', full_name='nats_schema.RequestInt64.Int64', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=252,
)


_REQUESTBYTES = _descriptor.Descriptor(
  name='RequestBytes',
  full_name='nats_schema.RequestBytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='nats_schema.RequestBytes.ID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Bytes', full_name='nats_schema.RequestBytes.Bytes', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=295,
)

DESCRIPTOR.message_types_by_name['SimpleMessage'] = _SIMPLEMESSAGE
DESCRIPTOR.message_types_by_name['MessageInt64'] = _MESSAGEINT64
DESCRIPTOR.message_types_by_name['MessageInt64Slice'] = _MESSAGEINT64SLICE
DESCRIPTOR.message_types_by_name['MessageBool'] = _MESSAGEBOOL
DESCRIPTOR.message_types_by_name['MessageBytes'] = _MESSAGEBYTES
DESCRIPTOR.message_types_by_name['RequestInt64'] = _REQUESTINT64
DESCRIPTOR.message_types_by_name['RequestBytes'] = _REQUESTBYTES

SimpleMessage = _reflection.GeneratedProtocolMessageType('SimpleMessage', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEMESSAGE,
  __module__ = 'simpleMessage_pb2'
  # @@protoc_insertion_point(class_scope:nats_schema.SimpleMessage)
  ))
_sym_db.RegisterMessage(SimpleMessage)

MessageInt64 = _reflection.GeneratedProtocolMessageType('MessageInt64', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEINT64,
  __module__ = 'simpleMessage_pb2'
  # @@protoc_insertion_point(class_scope:nats_schema.MessageInt64)
  ))
_sym_db.RegisterMessage(MessageInt64)

MessageInt64Slice = _reflection.GeneratedProtocolMessageType('MessageInt64Slice', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEINT64SLICE,
  __module__ = 'simpleMessage_pb2'
  # @@protoc_insertion_point(class_scope:nats_schema.MessageInt64Slice)
  ))
_sym_db.RegisterMessage(MessageInt64Slice)

MessageBool = _reflection.GeneratedProtocolMessageType('MessageBool', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEBOOL,
  __module__ = 'simpleMessage_pb2'
  # @@protoc_insertion_point(class_scope:nats_schema.MessageBool)
  ))
_sym_db.RegisterMessage(MessageBool)

MessageBytes = _reflection.GeneratedProtocolMessageType('MessageBytes', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEBYTES,
  __module__ = 'simpleMessage_pb2'
  # @@protoc_insertion_point(class_scope:nats_schema.MessageBytes)
  ))
_sym_db.RegisterMessage(MessageBytes)

RequestInt64 = _reflection.GeneratedProtocolMessageType('RequestInt64', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTINT64,
  __module__ = 'simpleMessage_pb2'
  # @@protoc_insertion_point(class_scope:nats_schema.RequestInt64)
  ))
_sym_db.RegisterMessage(RequestInt64)

RequestBytes = _reflection.GeneratedProtocolMessageType('RequestBytes', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTBYTES,
  __module__ = 'simpleMessage_pb2'
  # @@protoc_insertion_point(class_scope:nats_schema.RequestBytes)
  ))
_sym_db.RegisterMessage(RequestBytes)


# @@protoc_insertion_point(module_scope)
